name: dart_funcoes_colecoes
description: Modulo da Academia do Flutter de Funções e Coleções
version: 1.0.0
repository: instituto.academiadoflutter.com.br

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
